[package]
name = "zh-draft"
version = "0.0.1"
compiler = "0.14.0"
repository = "https://github.com/lvyuemeng/"
entrypoint = "lib.typ"
authors = ["lvyuemeng <lv15623448685@gmail.com>"]
license = "MIT"
description = "A tool-kit containing components and utilities suitable for thesis in China."
keywords = ["chinese", "cn", "kit", "component", "中文", "组件"]
exclude = ["example/"]
